theme: jekyll-theme-slate
show_downloads: false
title: Free for COVID
description: A collection of tools and software provided for free for those contributing to alleviating the COVID-19 pandemic. Feel free to contribute to this list by making a pull request or reaching out to Helpful Engineering!
